services:
  php:
    build:
      context: .
      target: php
      dockerfile: docker/Dockerfile
      args:
        uid: '${WWWUSER}'
    environment:
      - APACHE_RUN_USER=#${WWWUSER}
      - APACHE_RUN_GROUP=#${WWWUSER}
    ports:
      - 8080:80
      - 5173:5173
    networks:
      - internal
    volumes:
      - ./:/var/www/html:rw
    restart: unless-stopped
    depends_on:
      - mariadb
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80']
      interval: 30s
      timeout: 10s
      retries: 3

  mariadb:
    image: 'mariadb:10'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'data-mariadb:/var/lib/mysql'
    networks:
      - internal
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      PMA_USER: '${DB_USERNAME}'
      PMA_PASSWORD: '${DB_PASSWORD}'
    ports:
      - 8081:80
    depends_on:
      - mariadb
    networks:
      - internal

networks:
  internal:
    name: laravel-net
    driver: bridge

volumes:
  data-mariadb:
    driver: local
